# Fichier httpyac pour tester l'API services MeshOrbit

@host = http://localhost:3000

### Liste des services
GET {{host}}/services

### Création d'un service
# @name CreateService
POST {{host}}/services
Content-Type: application/json

{
  "name": "Service Test",
  "url": "http://localhost:4000",
  "status": "up"
}

### Détail d'un service
# @ref CreateService
GET {{host}}/services/{{CreateService.id}}

### Mise à jour d'un service
# @ref CreateService
PUT {{host}}/services/{{CreateService.id}}
Content-Type: application/json

{
  "name": "Service Test Updated",
  "url": "http://localhost:4000",
  "status": "down"
}

### Suppression d'un service
# @ref CreateService
DELETE {{host}}/services/{{CreateService.id}}
?? status == 200
?? body id == {{CreateService.id}}
